### PR TITLE
Add 'strip' option and tests.

### PR DESCRIPTION
**Pull request by ryan-roemer**
As an alternative to #6 , I've added a `strip` option to the plugin that applies the heuristic of:
- Remove all empty lines before first real character.
- Capture whitespace on line of first real char up to the char.
- Remove prefix of that captured indent token up to char on all subsequent
  lines.
- Remove white-space only lines at the very end of the snippet.

This PR
- Adds the `strip` option and tests
- Moves existing tests into describe blocks (apologies for extra diff that entails -- reviewing with [`?w=1`](https://github.com/FormidableLabs/gulp-html-extract/pull/7/files?w=1) should make easier)
- Replaces `gulpfile.js` for command line mocha + eslint (apologies for extra diff here -- the gulp mocha was making failures to hard to diagnose in CI)

@robdodson -- Does this meet your use case?

### CODE REVIEW

**Comment by robdodson** [comment]
Wow this looks great, let me give it a shot and report back!

**Comment by robdodson** [comment]
This looks good to me! +1 for merge :+1:

**Comment by samccone** [comment]
aww snap awesome work @ryan-roemer A+

**Comment by robdodson** [comment]
one quick question: would it be possible to insert a newline at the end of the extracted output? Right now jscs fails on this because of the `requireLineFeedAtFileEnd` rule.

**Comment by ryan-roemer** [comment]
@robdodson -- I'll add the newline. I'm thinking of having it not be an unconditional newline, but rather something like:

``` js
return text === "" ? "" : text + EOL;
```

Does that sound right for your use cases?  Or do you need "always" a newline with something like:

``` js
return text + EOL;
```

**Comment by robdodson** [comment]
yeah that seems ok. For sure if it's empty text it doesn't need a newline

**Comment by ryan-roemer** [comment]
@robdodson -- Can you check if the behavior in https://github.com/FormidableLabs/gulp-html-extract/commit/36b508e6579c799d39cb59534d2f03b44763a166 now pushed here is what you'd like?

**Comment by ryan-roemer** [comment]
I'm just going for it as CI is passed. Anyone can let me know if I've missed a corner case here ;)

**Comment by ryan-roemer** [comment]
Released as `gulp-html-extract@0.1.0`

**Comment by robdodson** [comment]
Awesome thank you @ryan-roemer

**Pull request merged**
